cache_dir: "/data/"
bind: "0.0.0.0:8000"
logging:
  level: "debug"
  format: "pretty"
  enable_backtraces: true
sources:
  # FIXME: This can point directly to S3 buckets.
  - id: "tecken"
    type: "http"
    url: "https://symbols.mozilla.org/"
# metrics:
  # statsd: "127.0.0.1:8125"
  # prefix: "symbolicator"
