version: "2"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    env_file:
      - my.env
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data

  # Shell for system tests and other experimentation
  systemtests:
    build:
      context: .
      dockerfile: systemtests/Dockerfile
    env_file:
      - my.env
    volumes:
      - .:/app
